name: flutter_time_tracker
description: Time-Tracker application for Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.2
  provider: ^6.0.2

  # Google
  google_sign_in: ^5.2.4
  google_fonts: ^2.3.1

  # FlutterFire
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  cloud_firestore: ^3.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true